---
title: 'Final Report: Bike-Sharing Data Analysis'
subtitle: "MA 575 Fall 2021 - C3 Team #2"
author: "Ali Taqi, Hsin-Chang Lin, Huiru Yang, Ryan Mahoney, Yulin Li"
date: "12/09/2021"
output: 
  pdf_document: 
    number_sections: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center")
#==============================#
#       Import Libraries       #
#==============================#
library(tidyverse)
library(GGally)
library(cowplot)
library(gglm)
library(moderndive)
#==============================#
#        Global Settings       #
#==============================#
# Center ggplot titles
theme_update(plot.title = element_text(hjust = 0.5))
#=============================#
#        Obtain Dataset       #
#=============================#
# Source the wrangling scripts
source(file = "../R/wrangle-lynne.R")
# Import and wrangle data
bike_day <- read.csv("../data/bike-day.csv", header = T)
# Use the wrangling "wrapper" function to clean the data (fxn sourced from wrangle.R)
data <- wrangle_init(bike_day)
# Partition the 2011/2012 data
data2011 <- in_2011(data); data2012 <- in_2012(data)
#============================#
#       Source Scripts       #
#============================#
# Import any models (and fitted values, if applicable)
source(file = "../R/model-lynne.R")
# Import any plots or plot wrapper functions
source(file = "../R/plot-lynne.R")
```

```{r}
.parseFormula <- function(predictors, response = "cnt"){
  f <- as.formula(
        paste(response, 
              paste(predictors, collapse = " + "), 
              sep = " ~ "))
  return(f)
}
```

```{r}
LOOCV <- function(predictors, response, train_data){
  is <- 1:nrow(train_data)
  residuals <- purrr::map_dbl(is, function(i){.LOOCV_i(i, predictors, response, train_data)})
  res_table <- data.frame(i = is, residual = residuals)
  return(res_table)
}
```

```{r}
.LOOCV_i <- function(i, predictors, response, train_data){
  # Choose observation i as our test data
  test_data <- train_data[i,]
  # Omit it from the training data
  train_data <- train_data %>% anti_join(test_data)
  # Parse the predictor string vector into a formula then fit the model
  model <- lm(formula = .parseFormula(predictors, response), data = train_data)
  # Evaluate the residual of the omitted observation
  yhat <- predict(model, test_data)
  y <- test_data[[response]]
  epsilon <- (yhat - y)
  # Return the residual
  return(epsilon)
}
```

```{r}
LOOCV_residuals <- purrr::map_dbl(.x = 1:nrow(data2011), .f = function(i){.LOOCV_i(i, varset1, data2011)})
plot(LOOCV_residuals)
```

## Explicit Formula and Sampling Fraction of Testing Data

```{r}
cross_validate <- function(predictors, train_data, p){
  test_data <- train_data %>% sample_frac(size = p)
  train_data <- train_data %>% anti_join(test_data)
  f <- .parseFormula(predictors)
  model <- lm(f, data = train_data)
  list(model, train_data, test_data)
}
```

```{r}
cross_validate1 <- function(predictors, train_data, p){
  ls <- cross_validate(predictors, train_data, p)
  test_data <- ls[[3]]
  yhat <- predict(ls[[1]], test_data)
  y <- test_data[["cnt"]]
  y - yhat
}
```

```{r}
#cross_validate(varset1, data2011, p = 1/365)
#cross_validate1(varset1, data2011, p = 1/365)
```

```{r}

```

