---
title: "Dev Template"
author: "Group 2"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center")
#==============================#
#       Import Libraries       #
#==============================#
library(tidyverse)
library(GGally)
library(cowplot)
#==============================#
#        Global Settings       #
#==============================#
# Center ggplot titles
theme_update(plot.title = element_text(hjust = 0.5))
#=============================#
#        Obtain Dataset       #
#=============================#
# Source the wrangling scripts
source(file = "../R/wrangle.R")
# Import and wrangle data
bike_day <- read.csv("../data/bike-day.csv", header = T)
# Use the wrangling "wrapper" function to clean the data (fxn sourced from wrangle.R)
data <- wrangle_init(bike_day)
# Partition the 2011/2012 data
data2011 <- in_2011(data)
data2012 <- in_2012(data)
#============================#
#       Source Scripts       #
#============================#
# Import any models (and fitted values, if applicable)
source(file = "../R/model.R")
# Import any plots or plot wrapper functions
source(file = "../R/plot.R")
```

## Autocorrelation (AR1) Model 

```{r}
# Wrangling function automatically tosses away "instant" variable so get it back
data <- wrangle_init(data = bike_day, omit_idx = FALSE)
# Partition the 2011/2012 data
data2011 <- in_2011(data); data2012 <- in_2012(data)
```

```{r}
# Fit the AR(1) model
m.gls <- gls(cnt ~ atemp + I(atemp^2) + holiday + weathersit, 
             data = data, 
             correlation = corAR1(form = ~instant), 
             method = "ML")
summary(m.gls)
```



