---
title: "Plot example"
author: "Group 2"
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = "center")
#==============================#
#       Import Libraries       #
#==============================#
library(tidyverse)
library(GGally)
library(cowplot)
#==============================#
#        Global Settings       #
#==============================#
# Center ggplot titles
theme_update(plot.title = element_text(hjust = 0.5))
#=============================#
#        Obtain Dataset       #
#=============================#
# Source the wrangling scripts
source(file = "../R/wrangle.R")
# Import and wrangle data
bikedata <- read.csv("../data/bike-day.csv", header = T)
# Use the wrangling "wrapper" function to clean the data (fxn sourced from wrangle.R)
data <- wrangle_init(bikedata)
#============================#
#       Source Scripts       #
#============================#
# Import any models (and fitted values, if applicable)
source(file = "../R/model_example.R")
# Import any plots or plot wrapper functions
source(file = "../R/plot_example.R")
```

```{r}
# Note: the code below (Prepare Plots) is redundant since it is already sourced in "plot.R". However, it is a prerequisite to run the code below before using the OLS_temp_plot function since it depends on them being there already. So, code below is just for demonstration
#===========================#
#       Prepare Plots       #
#===========================#
# Ordered color vector indexed by model
col_vec <- c('Linear' = "cyan", 'Quadratic' = "blue", 'Cubic' = "red", 'Quartic' = 'black')
# Create a list (vector of anything, even vectors!) of all the fitted values indexed by model
# Note: this is used by the wrapper function to access the appopriate vector of fitted values.
# i.e. fitted_vals1 = LS_fitvals[[1]] (Note: double bracket notation is for accessing lists as opposed to vectors)
LS_fitvals <- list(fitted_vals1, fitted_vals2, fitted_vals3, fitted_vals4) 

#===========================#
#        Obtain Plots       #
#===========================#
# Obtain the four plots from each OLS model (uses plotting wrapper function found in plot.R)
plot1 <- OLS_temp_plot(data, 1)
plot2 <- OLS_temp_plot(data, 2)
plot3 <- OLS_temp_plot(data, 3)
plot4 <- OLS_temp_plot(data, 4)
# Put the four plots in a grid
plot_grid(plot1, plot2, plot3, plot4)
# Directly call upon plots defined in plots.R
all_model_plot
```


