---
title: 'Lab Report: Bike-Sharing Data Analysis'
subtitle: "MA 575 Fall 2021 - C3 Team #2"
author: "Ali Taqi, Hsin-Chang Lin, Huiru Yang, Ryan Mahoney, Yulin Li"
date: "12/01/2021"
output: 
  pdf_document: 
    number_sections: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center", fig.height = 4, fig.width = 6)
#==============================#
#       Import Libraries       #
#==============================#
library(tidyverse)
library(GGally)
library(cowplot)
library(gglm)
library(moderndive)
#==============================#
#        Global Settings       #
#==============================#
# Center ggplot titles
theme_update(plot.title = element_text(hjust = 0.5))
#=============================#
#        Obtain Dataset       #
#=============================#
# Source the wrangling scripts
source(file = "../R/wrangle-lynne.R")
# Import and wrangle data
bike_day <- read.csv("../data/bike-day.csv", header = T)
# Use the wrangling "wrapper" function to clean the data (fxn sourced from wrangle.R)
data <- wrangle_init(bike_day)
# Partition the 2011/2012 data
data2011 <- in_2011(data); data2012 <- in_2012(data)
#============================#
#       Source Scripts       #
#============================#
# Import any models (and fitted values, if applicable)
source(file = "../R/model-lynne.R")
# Import any plots or plot wrapper functions
source(file = "../R/plot.R")
source(file = "../R/plot-lynne.R")
```

```{r}
rates_1 <- function(xs){
  rng <- 2:nrow(xs)
  rates <- xs$cnt[rng]/xs$cnt[rng - 1]
  rates
}
```

```{r}
data2011 <- data2011 %>% mutate(week = ceiling(1:nrow(data2011)/7))
data2012 <- data2012 %>% mutate(week = ceiling(1:nrow(data2012)/7))
```

```{r}
weekly_avgs <- function(data, var){
  weekly_cnts <- 
    data %>% 
      group_by(week) %>%
      summarize(wavg = mean({{ var }}))
  weekly_cnts$week <- weekly_cnts$week + 1
  weekly_cnts %>% filter(week <= 53)
}

cnt_avgs <- weekly_avgs(data2011, cnt)
colnames(cnt_avgs)[2] <- "wavg_cnt"
reg_avgs <- weekly_avgs(data2011, registered)
colnames(reg_avgs)[2] <- "wavg_reg"
cas_avgs <- weekly_avgs(data2011, casual)
colnames(cas_avgs)[2] <- "wavg_cas"
```


```{r}
join_weekly_avgs <- function(data, weekavgs){data %>% right_join(weekavgs, by = week)}
```

```{r}
data2011 <- data2011 %>% left_join(cnt_avgs)
data2011 <- data2011 %>% left_join(reg_avgs)
data2011 <- data2011 %>% left_join(cas_avgs)
```

```{r}
data2012 <- data2012 %>% left_join(cnt_avgs)
data2012 <- data2012 %>% left_join(reg_avgs)
data2012 <- data2012 %>% left_join(cas_avgs)
```
```{r}
write.csv(x = data2011, file = "data2011_G.csv")
```

```{r}
write.csv(x = data2012, file = "data2012_G.csv")
```







```{r}
data2011 <- data2011 %>% mutate(week = ceiling(1:nrow(data2011)/7))
# Get weekly averages
weekly_cnts <- 
  data2011 %>% 
    group_by(week) %>%
    summarize(cnt = mean(cnt))
# Take out last week
weekly_cnts <- weekly_cnts[1:52,]
# Get 1-delta growth rates
weekly_growth <- rates_1(weekly_cnts)
# Filter out any bad weeks
data2011_W <- data2011 %>% filter(week %in% 2:52)
```

```{r}
# Create the columns
growths <- do.call("c", map(weekly_growth, .f = function(x){rep(x,7)}))
avgs <- do.call("c", map(weekly_cnts$cnt[2:52], .f = function(x){rep(x,7)}))
# Append the columns
data2011_W$growths <- growths
data2011_W$avgs <- avgs
```

```{r}
write.csv(x = data2011_W, file = "data2011_G.csv")
```

```{r}
write.csv(x = data2012_W, file = "data2012_G.csv")
```

```{r}
data2012 <- data2012 %>% mutate(week = ceiling(1:nrow(data2012)/7))
# Get weekly averages
weekly_cnts <- 
  data2012 %>% 
    group_by(week) %>%
    summarize(cnt = mean(cnt))
# Take out last week
weekly_cnts <- weekly_cnts[1:52,]
# Get 1-delta growth rates
weekly_growth <- rates_1(weekly_cnts)
# Filter out any bad weeks
data2012_W <- data2012 %>% filter(week %in% 2:52)
```

```{r}
# Create the columns
growths <- do.call("c", map(weekly_growth, .f = function(x){rep(x,7)}))
avgs <- do.call("c", map(weekly_cnts$cnt[2:52], .f = function(x){rep(x,7)}))
# Append the columns
data2012_W$growths <- growths
data2012_W$avgs <- avgs
```

```{r}
write.csv(x = data2012_W, file = "data2012_G.csv")
```