---
title: 'Lab Report: Bike-Sharing Data Analysis'
subtitle: "MA 575 Fall 2021 - C3 Team #2"
author: "Ali Taqi, Hsin-Chang Lin, Huiru Yang, Ryan Mahoney, Yulin Li"
date: "12/01/2021"
output: 
  pdf_document: 
    number_sections: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center", warning = F, message = F, fig.height = 4, fig.width = 6)
#==============================#
#       Import Libraries       #
#==============================#
library(tidyverse)
library(GGally)
library(cowplot)
library(gglm)
library(moderndive)
library(lemon)
knit_print.data.frame <- lemon_print
#==============================#
#        Global Settings       #
#==============================#
# Center ggplot titles
theme_update(plot.title = element_text(hjust = 0.5))
#=============================#
#        Obtain Dataset       #
#=============================#
# Source the wrangling scripts
source(file = "wrangle.R")
# Import and wrangle data
bike_day <- read.csv("../data/bike-day.csv", header = T)
# Use the wrangling "wrapper" function to clean the data (fxn sourced from wrangle.R)
data <- wrangle_init(bike_day)
# Partition the 2011/2012 data
data2011 <- in_2011(data); data2012 <- in_2012(data)
# Add the weekly average columns
data2011 <- data2011 %>% add_weekly_averages
data2012 <- data2012 %>% add_weekly_averages
#============================#
#       Source Scripts       #
#============================#
# Import any models (and fitted values, if applicable)
source(file = "model.R")
source(file = "model-wk.R")
source(file = "model-tot.R")
source(file = "diagnostics.R")
# Import any plots or plot wrapper functions
source(file = "plot.R")
```

```{r}
#gridExtra::grid.arrange(p1, p2, p3, p4)

```


## Modeling

```{r}
.parseFormula <- function(predictors, response = "cnt"){
  f <- as.formula(
        paste(response, 
              paste(predictors, collapse = " + "), 
              sep = " ~ "))
  return(f)
}
```

```{r, echo = TRUE}
lm.tot <- function(varset, train_data = data2011){
  model <- lm(formula = .parseFormula(predictors = varset, response = "cnt"), data = train_data)
  model
}
lm.cas <- function(varset, train_data = data2011){
  model <- lm(formula = .parseFormula(predictors = varset, response = "casual"), data = train_data)
  model
}
lm.reg <- function(varset, train_data = data2011){
  model <- lm(formula = .parseFormula(predictors = varset, response = "registered"), data = train_data)
  model
}
evaluate_model <- function(cas, reg){
  get_mod_eval(cas, reg, data2011, data2012 %>% filter(dteday != '2012-10-29'), scale_2012 = FALSE)
}
```

```{r message=FALSE, warning=FALSE, render = lemon_print}
# Choose predictors
varset0 <- c("season:workingday:atemp", "weathersit:season", "holiday", "wavg_cas")
varset1 <- c("season:workingday:atemp", "season:workingday:I(atemp^2)", "weathersit", "holiday", "wavg_reg")
# Fit the linear models
mod.cas.3.5.5 <- lm.cas(varset0)
mod.reg.4.0.5 <- lm.reg(varset1)
# Evaluate them
evaluate_model(mod.cas.3.5.5, mod.reg.4.0.5)
```

```{r}
res_table <- LOOCV(varset0, "casual", data2011, summarize = F)
res_table
rmse <- LOOCV(varset0, "casual", data2011, summarize = T)
rmse
```

```{r message=FALSE, warning=FALSE, render = lemon_print}
mod.cas.3.5.5.5 <- lm.cas(c(varset0,"weekday"), data2011)
mod.reg.4.0.5.5 <- lm.reg(c(varset1,"weekday"), data2011)
evaluate_model(mod.cas.3.5.5.5, mod.reg.4.0.5.5)
```

#### Modeling the Total Count

```{r, echo = TRUE}
evaluate_tot_model <- function(tot, train_data = data2011, test_data = data2012, scale_2012 = TRUE){
  get_mod_eval_tot(tot, train_data, test_data %>% filter(dteday != '2012-10-29'), scale_2012 = scale_2012)
}
```

```{r message=FALSE, warning=FALSE, render = lemon_print}
evaluate_tot_model(mod.tot.3)
```

##### With the weekly average: 

```{r, echo = TRUE}
evaluate_tot_model_v2 <- function(tot){
  evaluate_tot_model(tot, train_data = data2011, test_data = data2012, scale_2012 = FALSE)
}
```

```{r message=FALSE, warning=FALSE, render = lemon_print}
evaluate_tot_model_v2(mod.tot.3.0.5)
```

##### With the weekly average and weekday:

```{r message=FALSE, warning=FALSE, render = lemon_print}
evaluate_tot_model_v2(mod.tot.3.0.5.5)
```

#### Model Evals

```{r}
evaluate_model_v2 <- function(cas, reg){
  get_mod_eval(cas, reg, data2011, data2012 %>% filter(dteday != '2012-10-29'), scale_2012 = FALSE)
}
```

```{r message=FALSE, warning=FALSE, render = lemon_print}
evaluate_model_v2(mod.cas.2.7, mod.reg.4)
```







