---
title: 'Bike-Sharing Data Analysis: Prediction of Daily Bike Rental Counts Based on Multiple Linear Regression'
subtitle: "Final Project Report · MA 575 Fall 2021 · C3 · Team #2"
author: "Ali Taqi, Hsin-Chang Lin, Huiru Yang, Ryan Mahoney, Yulin Li"
date: "12/10/2021"
output: 
  pdf_document: 
    number_sections: true
classoption: twocolumn
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center", warning = F, message = F, fig.height = 4, fig.width = 6)
#==============================#
#       Import Libraries       #
#==============================#
library(tidyverse)
library(GGally)
library(cowplot)
library(gglm)
library(moderndive)
library(lemon)
knit_print.data.frame <- lemon_print
#==============================#
#        Global Settings       #
#==============================#
# Center ggplot titles
theme_update(plot.title = element_text(hjust = 0.5))
#=============================#
#        Obtain Dataset       #
#=============================#
# Source the wrangling scripts
source(file = "wrangle.R")
# Import and wrangle data
bike_day <- read.csv("../data/bike-day.csv", header = T)
# Use the wrangling "wrapper" function to clean the data (fxn sourced from wrangle.R)
data <- wrangle_init(bike_day)
# Partition the 2011/2012 data
data2011 <- in_2011(data); data2012 <- in_2012(data)
# Add the weekly average columns
data2011 <- data2011 %>% add_weekly_averages
data2012 <- data2012 %>% add_weekly_averages
#============================#
#       Source Scripts       #
#============================#
# Import any models (and fitted values, if applicable)
source(file = "model-build.R")
source(file = "model.R")
source(file = "model-wk.R")
source(file = "model-tot.R")
source(file = "diagnostics.R")
# Import any plots or plot wrapper functions
source(file = "plot.R")
```

```{r}
.plot_counts <- function(data, user, compare = FALSE){
  ##########################
  ## Graphical parameters ##
  ##########################
  size0 <- 1.5; size1 <- 0.3
  pch0 <- 16; pch1 <- 20
  
  ###############
  ## Main plot ##
  ###############
  main_plot <- 
    data %>%
    ggplot(aes(x = dteday, y = .data[[user]], color = 'all day types')) + 
    geom_point(size = size0, pch = pch1, alpha = 0.8) + 
    # General plot settings
    labs(x = 'Date', y = 'Daily Registered Count', title = .title_helper(user)) + 
    theme_grey(base_size = 5.5) + 
    theme(plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5),
          plot.caption = element_text(hjust = 0.5)) +
    # Geoms
    geom_line(mapping = aes(x = dteday, .data[[user]], color = 'trends'), 
              size = size1, alpha = 0.8) + 
    geom_point(data %>% filter(!workingday), 
               mapping = aes(x = dteday, y = .data[[user]], color = 'on non-working days'), 
               size = size0, pch = pch0, alpha = 1) + 
    geom_point(data %>% filter(holiday), 
               mapping = aes(x = dteday, y = .data[[user]], color = 'on holidays'),
               size = size0, pch = pch0, alpha = 1) + 
    # Color settings
    scale_color_manual(values = cols, 
                       labels = names(cols), 
                       name = 'Daily Count')
  ################
  ## Comparsion ##
  ################
  # If other user type data series is not desired, return the main plot
  if(!compare){ return(main_plot) }
  # Otherwise, append the other user data before returning (at a lower alpha)
  main_plot +
    geom_line(data = data, 
              mapping = aes(x = dteday, y = .data[[.switch_user(user)]], color = 'trends'), 
              size = size1, alpha = 0.2) + 
    geom_point(data %>% filter(!workingday), 
               mapping = aes(x = dteday, y = .data[[.switch_user(user)]], color = 'on non-working days'), 
               size = size0, pch = pch0, alpha = 0.2) + 
    geom_point(data %>% filter(holiday), 
               mapping = aes(x = dteday, y = .data[[.switch_user(user)]], color = 'on holidays'), 
               size = size0, pch = pch0, alpha = 0.2)
}

.title_helper <- function(user){
  user_title <- str_to_title(user)
  paste("Daily User Count for ",user_title," Users", sep = "")
}

# Dummy helper function that returns a string of the other user type
.switch_user <- function(user){
  if(user == "registered"){ return("casual") }
  if(user == "casual"){ return("registered") }
  else{ warning("User type not found")}
}
```


```{r, fig.height = 4, fig.width = 4}
data2011 %>% .plot_counts(user = "registered", compare = T)
ggsave(filename = "graphics/reg-2011-simple.pdf")
```

