---
title: 'Lab Report: Bike-Sharing Data Analysis'
subtitle: "MA 575 Fall 2021 - C3 Team #2"
author: "Ali Taqi, Hsin-Chang Lin, Huiru Yang, Ryan Mahoney, Yulin Li"
date: "12/01/2021"
output: 
  pdf_document: 
    number_sections: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center", fig.height = 4, fig.width = 6)
#==============================#
#       Import Libraries       #
#==============================#
library(tidyverse)
library(GGally)
library(cowplot)
library(gglm)
library(moderndive)
#==============================#
#        Global Settings       #
#==============================#
# Center ggplot titles
theme_update(plot.title = element_text(hjust = 0.5))
#=============================#
#        Obtain Dataset       #
#=============================#
# Source the wrangling scripts
source(file = "../R/wrangle-lynne.R")
# Import and wrangle data
bike_day <- read.csv("../data/bike-day.csv", header = T)
# Use the wrangling "wrapper" function to clean the data (fxn sourced from wrangle.R)
data <- wrangle_init(bike_day)
# Partition the 2011/2012 data
data2011 <- in_2011(data); data2012 <- in_2012(data)
#============================#
#       Source Scripts       #
#============================#
source("growth.R")
```

```{r}
data <- data2011 %>% select(dteday, weathersit, holiday, atemp, hum, windspeed, "cnt")
data <- data %>% mutate_at(c("atemp", "hum", "windspeed"), ~(scale(.) %>% as.vector))
data <- data %>% filter(!holiday)
```

```{r}
pairs <- .unique_pairs_lower(nrow(data))
```

```{r}
env_diffs <- map2_dfr(pairs[["i"]], pairs[["j"]], .f = function(i,j){data.frame(i = i, j = j, day_diff = envir_diff_ij(i,j))})
env_diffs <- env_diffs %>% mutate(idx_diff = i - j)
```

```{r}
#write.csv(env_diffs, "envdiffs.csv")
```

```{r}
g_estimate <- function(idx_bound, loss_bound, g_bound = 4){
  sset <- env_diffs %>% filter(idx_diff > idx_bound) %>% filter(day_diff < loss_bound)
  sset <- sset %>% mutate(g = growth_ratio(i, j))
  #env_diffs_sset2 <- env_diffs_sset2 %>% filter(g < g_bound)
  list(mean(sset$g), nrow(sset))
}
```

```{r}
g_estimate(300, loss_bound = 3.5)
```

```{r}
idx_bds <- seq(122, 365, 8)
loss_bds <- seq(1, 4, 0.10)
MIP <- .unique_pairs_lower(length(idx_bds))
```

```{r}
helper_fxn0 <- function(k){
  idx <- MIP$i[k]
  loss <- MIP$j[k]
  results <- g_estimate(idx, loss)
  data.frame(idx_bd = idx_bds[idx], loss_bd = loss_bds[loss], g = results[[1]], n = results[[2]])
}
paramater_df <- map_dfr(1:nrow(MIP), helper_fxn0)
```

```{r}
paramater_df %>%
  ggplot() +
  geom_point(aes(x = idx_bd, y = loss_bd, color = g))
```

```{r}
paramater_df %>%
  filter(idx_bd > 10, loss_bd < 5) %>%
  ggplot() +
  geom_point(aes(color = idx_bd, x = loss_bd, y = g, alpha = 1 - (1.5 - (62000/2*62000 - 1.35*n)))) +
  geom_abline(slope = 0, intercept = 3.35) +
  theme(legend.position = "none")
```

```{r}
hist(paramater_df$g)
```

```{r}
env_diffs_sset <- env_diffs %>% filter(idx_diff > 300) %>% filter(day_diff < 1.75)
env_diffs_sset2 <- env_diffs_sset %>% mutate(g = growth_ratio(i, j))
env_diffs_sset2 <- env_diffs_sset2 %>% filter(g < 4)
mean(env_diffs_sset2$g)
```

```{r}
env_diffs %>%
  ggplot() +
  geom_point(aes(x = i, y = j, color = day_diff))
```

## Window Technique

```{r}
envir_diff_ij(1,180)
```

```{r}
window_g <- function(w, no_outlier = T){
  lower_idx <- 1:w
  upper_idx <- 366 - (w:1)
  last_w <- data2011[upper_idx,]
  first_w <- data2011[lower_idx,]
  if(no_outlier){ first_w <- first_w %>% filter(dteday != "2011-1-3") }
  mean(last_w$cnt)/mean(first_w$cnt)
}
```

```{r}
window_vals<- purrr::map_dbl(1:20, window_g)
window_vals[6]
1/min(window_vals)
```

```{r}
window_tbl<- purrr::map_dfr(1:20, function(w){data.frame(w = w, g_w = window_g(w))})
window_tbl %>%
  ggplot() +
  geom_point(aes(w, g_w))

window_tbl<- purrr::map_dfr(1:20, function(w){data.frame(w = w, g_w = window_g(w, no_outlier = F))})

window_tbl %>%
  ggplot() +
  geom_point(aes(w, g_w))

```

```{r}
w <- 6
idx <- 366-(w:1)
first_10 <- data2011[c(1:w),]
first_10 <- first_10 %>% filter(dteday != "2011-1-3")
last_10 <- data2011[idx,]
mean(last_10$cnt)/mean(first_10$cnt)
```


